//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC_Demo_100524.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int id { get; set; }
        public string empName { get; set; }
        public string dept { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
